# Generated by Django 4.2.23 on 2025-09-01 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='temp_files/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('share_token', models.CharField(max_length=32, unique=True)),
                ('expiry_minutes', models.IntegerField(choices=[(5, '5 دقیقه'), (30, '30 دقیقه'), (60, '1 ساعت')], default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('download_count', models.IntegerField(default=0)),
                ('max_downloads', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'temp_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('temp_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='file_sharing.tempfile')),
            ],
            options={
                'db_table': 'download_logs',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
